safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vendor']

url: http://6th-ndn-hackathon.named-data.net
baseurl:

plugins:
  - jekyll-assets
  - jekyll-last-modified-at

deadlines:
        - name: Submission deadline
          date: <del>April 27, 2018</del>
        - name: Acceptance notification
          date: <del>May 4, 2018</del>

# Configuration for permalink
permalink: /:page.html

# Configuration for site
title: 6th Named Data Networking (NDN) Hackathon
short_title: 6th NDN Hackathon
description: May 12-13, 2018, Florida International University
author: 6th NDN Hackathon Organizing Committee
email: 6th-ndn-hackathon@named-data.net

# Configuration for blog
lang: en
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
# - name: Call for Hack Proposals
#   link: /cfh.html
- name: Committees
  link: /committees.html
- name: Terms
  link: /terms.html

#- name: Call for Hacks
#  link: /cfh.html
- name: Program
  link: /program.html

#- name: <b>REGISTER NOW</b>
#  link: https://www.eventbrite.com/e/6th-ndn-hackathon-tickets-43721926459
- name: <b>HACKS</b>
  link: /hacks.html

- name: <b>PHOTOS</b>
  link: /photos.html
#- name: Judging
#  link: /judging.html

asides:
    github: true
    tweets: false
    archive_tabs: false

google_plus_one:
    size: medium

twitter:
    username: NamedData
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false
    widget_id: 698294519054278656

github:
   username: 6th-ndn-hackathon
   count: 10000

assets:
  cache: .sass-cache
  features:
    automatic_img_size: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/files

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
